src/objects/Cloud_News__e.object
<CustomObject>
    <description>Cloud news events deliver news at your fingertips</description>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>News_Content__c</fullName>
        <label>News Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Urgent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Urgent</label>
        <type>Checkbox</type>
    </fields>
    <label>Cloud News</label>
    <pluralLabel>Cloud News</pluralLabel>
</CustomObject>

src/classes/CN_CloudNewsTriggerIntTest.cls
@isTest
public with sharing class CN_CloudNewsTriggerIntTest {
	private static final User TestRunner = TEST_RunAsUserFactory.create(); 
	
    @isTest public static void testCloudNewsTriggerShouldCreateCases() {
    	// Arrange
    	Group testGroup = new Group(name = 'Regional Dispatch', type = 'Queue');
    	insert testGroup;
    	insert new QueuesObject(queueId = testGroup.id, SObjectType = 'Case');
    	
    	Cloud_News__e testCloudNews = new Cloud_News__e(
    		Location__c = 'Mountain City',
    		News_Content__c = 'Test message.',
    		Urgent__c = true
    	); 
    	
		// Act
		Database.SaveResult saveResult;
        Test.startTest();
        System.runAs(TestRunner){
        	saveResult = EventBus.publish(testCloudNews);
        }
        Test.stopTest();

		// Assert
		List<Case> caseList = [SELECT id FROM Case];
		System.assertEquals(1, caseList.size());
    }
}